---
# Pod
apiVersion: v1
kind: Pod
metadata:
  name: postgressql
  labels:
    app: sql
spec:
  containers:
  - name: postgressql
    image: postgres:9.6.2-alpine
    ports:
     - name: pod-api
       containerPort: 5432
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
           name: secrets # => References the secret name
           key:  user    # => References a key from the secret
