---
apiVersion: extensions/v1beta1
kind:       Deployment
metadata:
  name: icono
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: icono
    spec:
      containers:
      - name:  icono
        image: quay.io/imhotepio/iconoflix:mem
        resources: # Must define resource limits for hpa to work!!
          requests:
            memory: 64Mi
            cpu:    250m
          limits:
            memory: 128Mi
            cpu:    250m
        ports:
        - name: pod-api
          containerPort: 4000
---
# Autoscaler
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: icono
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: icono
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 2