---
# Deployment
apiVersion: extensions/v1beta1
kind:       Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name:            ui
        image:           quay.io/derailed/iconoflix-ui:0.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory:      64Mi
            cpu:         250m
          limits:
            memory:      128Mi
            cpu:         500m
        env:
        - name:  ICX_API_IP
          value: api
        - name:  ICX_API_PORT
          value: "30601"
        ports:
        - name:          http
          containerPort: 80
---
# Service
apiVersion: v1
kind:       Service
metadata:
  name: ui
  labels:
    app: ui
spec:
  selector:
    app: ui
  type: NodePort
  ports:
    - name:       http
      port:       80
      targetPort: http
      nodePort:   30601
