---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx # This must match to pod labels!
  type: ClusterIP
  ports:
    - name:       http
      port:       80
      targetPort: 80